services:
  - type: web_service
    name: configserver
    env: docker
    plan: free
    dockerImage: ajaysakpal/microservices1:practice-configserver-latest
    envVars:
      - key: CONFIG_SERVER_URL
        value: http://configserver:8085
    healthCheckPath: /actuator/health

  - type: web_service
    name: apigatewayservice
    env: docker
    plan: free
    dockerImage: ajaysakpal/microservices1:practice-apigatewayservice-latest
    envVars:
      - key: CONFIG_SERVER_URL
        value: http://configserver:8085
      - key: USERSERVICE_DOMAIN
        value: userdomainservice
    startCommand: ""
    healthCheckPath: /actuator/health

  - type: web_service
    name: userdomainservice
    env: docker
    plan: free
    dockerImage: ajaysakpal/microservices1:practice-userdomainservice-latest
    envVars:
      - key: CONFIG_SERVER_URL
        value: http://configserver:8085
    startCommand: ""
    healthCheckPath: /actuator/health
